version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt  # Install Python dependencies
  build:
    commands:
      - cdk synth  # Synthesize the CDK app
artifacts:
  files:
    - '**/*'
  base-directory: 'cdk.out'
